### ISSUE TITLE
fix tree heights file

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBI-ForestGEO-Data#13]
@gonzalezeb and @mcgregorian1,  [our tree height file](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_dimensions/tree_heights/SCBI_tree_heights.csv) has a problem -- sources/ researchers and their respective DOIs do not match. This should be easy to fix, but I'm not sure which columns to trust. Perhaps an older version of the file has this correct?

**Comment by mcgregorian1** [comment]
I can look into this this week

**Comment by mcgregorian1** [comment]
@teixeirak I've gone through Atticus' paper again and there is no mention of ground-truthed measurements, nor the methodology he described via email about using the clinometer. As this isn't part of the paper, the raw data file for the measurements we have in this heights.csv must be from somewhere on a local drive. Do you have an idea where?

Otherwise, I've updated his doi and removed the wrong sources for him, but I kept yours and Thompson's the same. I also updated the doc with the methods used and put some notes.

**Comment by teixeirak** [comment]
Thanks! I sent you Atticus’ original file by email.
