### ISSUE TITLE
Problems with Fast Fields

### ISSUE THREAD

**Issue by briannakcalkins** [SCBI-ForestGEO/SCBI-ForestGEO-Data#31]
Hello everyone, I have been running into an issue with Fast Fields the last few times I've been into the field. After making the latest update on the form we use at SCBI, I can now not really edit the previous forms I had in progress (for example the quadrats split by the deer exclosure). This issue arises also when errors are dispatched to the iPads. When opening up the form to edit, and adding a new stem, none of that stems information shows up besides it's stem number and identifier. So, the species name, width, last year status, etc are all just blank. Is there anyway to fix this? Thanks!

**Comment by teixeirak** [comment]
@jess-shue , this is a question for you.

**Comment by jess-shue** [comment]
@briannakcalkins @teixeirak This is due to updating the app. When you attempt to edit a form created in the older version the app no longer has that data/format and so it no longer functions properly. 
I had asked if there were forms in progress but had not gotten a response, I'm sorry about that. Editing older forms that must be re-dispatched will cause the similar issues.

The 'in progress' forms would be the most important so those data aren't lost. There are a few options:  revert the app back to that version, making sure everyone else has completed their current forms, until they are complete. Or, you can copy over the data manually into the current version of the app - may require having two iPads (one with the in progress form and another to copy the form into).

We may need to set up a zoom to discuss as we all need to be on the same page for which version of the app is needed, or to at least make the best decision on how to proceed. Forms that were already submitted but require some type of edit I would suggest be submitted in the new version of the form.

**Comment by teixeirak** [comment]
@jess-shue , oh wow... this sounds like it may be a mess. We have plenty of errors that require re-dispatching quadrats (which I did not realize would count as in-progress): 
![image](https://user-images.githubusercontent.com/6355854/126983220-4234872b-3112-40e2-bcc5-761ef5b26851.png)

Copying over all the data does not seem like a feasible option. There have been so many form versions that reverting back to those does not seem feasible either (plus these were fixed because they had problems). Perhaps the best option would be to create a new form version with just the missed stems or stems with errors (after all quadrats have been censused)? Would that work?

**Comment by jess-shue** [comment]
@teixeirak Copying over the data would only be necessary for currently 'in-progress' quadrats - if they have some partially completed quadrats from last week I would use that option to complete those.

For errors and quadrats that need to be re-dispatched because they were already submitted:  I think this may be something where whomever is going to 'fix' those issues may just need to use the new version of the form. Are they currently taking a list of the errors along with the dispatched forms? How do they know what to correct in the dispatches? Simply using the new version and correcting only those stems with errors should be pretty straightforward. Instead of overwriting the previous form, this will create duplicates and the correction will have to be selected (the record with the error will need to be deleted).

Does that make sense? Making a new form with the errors is also possible, but likely best to compile all of the errors, or create an error form by column, to reduce the risk of app versions causing similar problems down the road.

**Comment by teixeirak** [comment]
Should re-dispatching work for missing stems (most of the errors), then? .I'm not sure if @briannakcalkins had any un-submitted forms or if she's talking about previous forms that she's re-dispatched.

For stems with errors, we have been fixing errors by re-dispatching and using the new version of the form. We do have a list of errors. That has been working fine.

**Comment by jess-shue** [comment]
@teixeirak @briannakcalkins  It sounds like there are three different scenarios to me:
1. Brianna has some quadrats that are split by the deer fence that weren't completed and were sitting in-progress. If these were started in a previous version of the app I would suspect there would be issues completing them. Do I have that right @briannakcalkins ?
2. Re-dispatched forms are not populating all of the data when adding a new stem (missed stem).
3. Re-dispatched forms are not populating all of the data when attempting to make some other type of correction.
If folks are simply opening the app and starting a new form to correct errors or add stems it should work just fine. The Re-dispatched forms in a previous app version are causing the problem - the app version on the tablet no longer recognizes the lookup mappings and cannot populate the data.
@briannakcalkins Am I following your first problem/comment correctly?

**Comment by briannakcalkins** [comment]
Hey @jess-shue so sorry for the late response, I have been dealing with a cold. Yes, correct, when trying to fix errors, it's just that when I pull up a new stem (to fill in for a missing one) it gives none of the data but for simply correcting errors it's just fine. Do you have any updates on how we can go about fixing any of these errors? Thanks

**Comment by jess-shue** [comment]
@briannakcalkins  This is within a form that has been re-dispatched to the iPad, correct? The issue is that the version of the form is older than the current form. The new form is using a new data file and the lookup mappings - when connecting the tag number to the rest of the data - are no longer working in the old version of the form.

Would you be available for a call or Zoom meeting sometime today? I think if we have a meeting we can work through how to move this ahead much easier than back-and-forth on here!

**Comment by briannakcalkins** [comment]
@jess-shue Yes I agree a zoom meeting would be easier! However, I won't be available today or tomorrow because of field work/ other commitments. How should we move forward?

**Comment by jess-shue** [comment]
@briannakcalkins One simple solution may be to correct missing stems and errors separately. If it is something entered incorrectly, dispatch that form, edit the error, and resubmit to overwrite the original. If it is a missing stem, I would simply create a new form using the updated version to enter data for that stem. This will produce a second submission for that quadrat, but it will have a new date in the name and only data for the missing (or multiple) missing stems. 

I'm sorry to force a separate form entry, but that may be the easiest solution.

**Comment by teixeirak** [comment]
This is a stale issue-- closing it.
