### ISSUE TITLE
calculate ANPP for 2013-18

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBI-ForestGEO-Data#6]
@ValentineHerr, could you please update the biomass and ANPP calculations to include 2013-18? The immediate purpose is for the Shenandoah paper.

**Comment by ValentineHerr** [comment]
2018 data is in a very different format than the previous years because it has not passed all steps with Suzanne. When she gives us a file called scbi.stem3.rdata this update will be very quick and easy but before then, it will require a lot more coding and time.

Do you know the time frame for Suzanne? Maybe @gonzalezeb knows.

@teixeirak, let me know if you still want me to give a push on that now and get to ANPP 13-18.

**Comment by teixeirak** [comment]
Not worth it until we have the data from Suzanne. Thanks for the explanation!
